# Site settings
title            : _THE_  spaghetti_code_ball

email            : vwwv@correo.ugr.es
timezone         : Etc/Universal
enconding        : utf-8
lsi              : true 

description      :  A Personal Programming Blog

long_description :  A Personal Programming Blog

baseurl          : "" # the subpath of your site, e.g. /blog/

url              : "http://the.spaghetticodeball.xyz" # the base hostname & protocol for your site

twitter_username : false

github_username  :  vwwv

# Build settings
markdown         : kramdown

production       : true
